import type { BuildingDef, BuildingId } from './schema';

/**
 * The building set. Since M9, buildings ARE the economy; since M12 the
 * economy is walked by VILLAGERS: `workplace` buildings offer slots to work
 * at (farms, markets), `dropoff` buildings receive the carried loads (town
 * center always; lumber camps and quarries near the resource shorten trips —
 * placement IS the gather rate). Every settlement is seeded with a Town
 * Center (seedOnly — never buildable) and a few houses; the rest is built.
 */
export const BUILDINGS: Record<BuildingId, BuildingDef> = {
  townCenter: {
    id: 'townCenter',
    name: 'Town Center',
    cost: {},
    buildTime: 1,
    hp: 800,
    requiresAge: 'founding',
    seedOnly: true,
    functions: [
      { kind: 'housing', capacity: 80 },
      { kind: 'storage', capacity: 500 },
      { kind: 'dropoff', resources: ['food', 'wood', 'stone', 'gold'] },
      { kind: 'fort', hp: 300 },
      { kind: 'training', units: ['militia'] },
    ],
    footprint: { w: 3, d: 3 },
  },
  house: {
    id: 'house',
    name: 'House',
    cost: { wood: 30 },
    buildTime: 60, // ticks (6 days)
    hp: 200,
    requiresAge: 'founding',
    functions: [{ kind: 'housing', capacity: 20 }],
    footprint: { w: 1, d: 1 },
  },
  farm: {
    id: 'farm',
    name: 'Farm',
    cost: { wood: 40 },
    buildTime: 80,
    hp: 150,
    requiresAge: 'founding',
    functions: [{ kind: 'workplace', resource: 'food', slots: 5 }],
    footprint: { w: 2, d: 2 },
  },
  lumberCamp: {
    id: 'lumberCamp',
    name: 'Lumber Camp',
    cost: { wood: 35 },
    buildTime: 60,
    hp: 150,
    requiresAge: 'founding',
    functions: [{ kind: 'dropoff', resources: ['wood'] }],
    footprint: { w: 2, d: 1 },
  },
  quarry: {
    id: 'quarry',
    name: 'Quarry',
    cost: { wood: 50 },
    buildTime: 100,
    hp: 200,
    requiresAge: 'founding',
    functions: [{ kind: 'dropoff', resources: ['stone'] }],
    footprint: { w: 2, d: 2 },
  },
  market: {
    id: 'market',
    name: 'Market',
    cost: { wood: 60, gold: 20 },
    buildTime: 90,
    hp: 180,
    requiresAge: 'founding',
    functions: [{ kind: 'workplace', resource: 'gold', slots: 5 }],
    footprint: { w: 2, d: 2 },
  },
  storehouse: {
    id: 'storehouse',
    name: 'Storehouse',
    cost: { wood: 80 },
    buildTime: 100,
    hp: 250,
    requiresAge: 'founding',
    functions: [
      { kind: 'storage', capacity: 500 },
      { kind: 'dropoff', resources: ['food', 'wood', 'stone', 'gold'] },
    ],
    footprint: { w: 2, d: 2 },
  },
  temple: {
    id: 'temple',
    name: 'Temple',
    cost: { wood: 80, stone: 100 },
    buildTime: 140,
    hp: 300,
    requiresAge: 'flowering',
    functions: [],
    effects: [{ stat: 'popGrowth', op: 'mul', value: 1.15 }],
    footprint: { w: 2, d: 3 },
  },
  granary: {
    id: 'granary',
    name: 'Granary',
    cost: { wood: 100 },
    buildTime: 110,
    hp: 220,
    requiresAge: 'flowering',
    functions: [
      { kind: 'storage', capacity: 400 },
      { kind: 'dropoff', resources: ['food'] },
    ],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.1, resource: 'food' }],
    footprint: { w: 2, d: 2 },
  },
  university: {
    id: 'university',
    name: 'University',
    cost: { wood: 150, stone: 120, gold: 100 },
    buildTime: 200,
    hp: 300,
    requiresAge: 'highKingdom',
    functions: [],
    effects: [{ stat: 'researchSpeed', op: 'mul', value: 1.25 }],
    footprint: { w: 3, d: 3 },
  },
  guildhall: {
    id: 'guildhall',
    name: 'Guildhall',
    cost: { wood: 120, gold: 80 },
    buildTime: 160,
    hp: 280,
    requiresAge: 'highKingdom',
    requiresTechs: ['caravans'],
    functions: [{ kind: 'workplace', resource: 'gold', slots: 5 }],
    footprint: { w: 2, d: 2 },
  },
  keep: {
    id: 'keep',
    name: 'Keep',
    cost: { stone: 300, gold: 150 },
    buildTime: 300,
    hp: 1200,
    requiresAge: 'golden',
    requiresTechs: ['architecture'],
    functions: [{ kind: 'fort', hp: 1200 }],
    footprint: { w: 3, d: 3 },
  },
  palisade: {
    id: 'palisade',
    name: 'Palisade',
    cost: { wood: 100 },
    buildTime: 120,
    hp: 500,
    requiresAge: 'founding',
    functions: [{ kind: 'fort', hp: 500 }],
    footprint: { w: 2, d: 1 },
  },
  stoneWall: {
    id: 'stoneWall',
    name: 'Stone Wall',
    cost: { stone: 250 },
    buildTime: 200,
    hp: 1500,
    requiresAge: 'highKingdom',
    requiresTechs: ['masonry'],
    functions: [{ kind: 'fort', hp: 1500 }],
    footprint: { w: 2, d: 1 },
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    cost: { wood: 60 },
    buildTime: 90,
    hp: 350,
    requiresAge: 'founding',
    functions: [{ kind: 'training', units: ['militia', 'spearman', 'swordsman', 'ram', 'huscarl'] }],
    footprint: { w: 3, d: 3 },
  },
  archeryRange: {
    id: 'archeryRange',
    name: 'Archery Range',
    cost: { wood: 80 },
    buildTime: 100,
    hp: 300,
    requiresAge: 'flowering',
    functions: [{ kind: 'training', units: ['archer', 'skirmisher'] }],
    footprint: { w: 3, d: 2 },
  },
  stable: {
    id: 'stable',
    name: 'Stable',
    cost: { wood: 100, gold: 20 },
    buildTime: 110,
    hp: 320,
    requiresAge: 'flowering',
    functions: [{ kind: 'training', units: ['lightCavalry', 'knight', 'paladin', 'camelRider'] }],
    footprint: { w: 3, d: 2 },
  },
  wonder: {
    id: 'wonder',
    name: 'Wonder',
    cost: { wood: 1000, stone: 2000, gold: 1500 },
    buildTime: 1200, // 120 days of labor — an age unto itself
    hp: 3000,
    requiresAge: 'golden',
    functions: [], // it does nothing; it IS the point (stand WONDER_DAYS → victory)
    footprint: { w: 4, d: 4 },
  },
};

export const BUILDING_IDS: readonly BuildingId[] = Object.keys(BUILDINGS);
