import type { Rng } from '../core/rng';
import { pick } from '../core/rng';
import type { NameBank } from './schema';

/**
 * The ANNALS name bank, kept as the culture-neutral default. Per-culture
 * banks (Valen/Norvik/Ashari) arrive with the cultures milestone.
 */
export const commonNames: NameBank = {
  place1: [
    'Vael',
    'Oster',
    'Bram',
    'Dun',
    'Ash',
    'Thorn',
    'Wyn',
    'Cael',
    'Grim',
    'Mor',
    'Hald',
    'Fen',
    'Bel',
    'Cor',
    'Ryn',
    'Ald',
    'Hel',
    'Wester',
    'Nor',
    'Eld',
    'Marl',
    'Stone',
    'Raven',
    'Bright',
    'Wind',
    'Frost',
    'Green',
    'Black',
  ],
  place2: [
    'mere',
    'holt',
    'ford',
    'caster',
    'wyck',
    'field',
    'burgh',
    'ton',
    'dale',
    'moor',
    'hollow',
    'reach',
    'watch',
    'fell',
    'marsh',
    'haven',
    'crest',
    'gate',
    'bourne',
    'stead',
  ],
  givenM: [
    'Aldric',
    'Edmund',
    'Corin',
    'Baldwin',
    'Osric',
    'Ranulf',
    'Gareth',
    'Roderic',
    'Alaric',
    'Tybalt',
    'Percival',
    'Godwin',
    'Halden',
    'Merrick',
    'Sigurd',
    'Bran',
    'Cedric',
    'Ewan',
    'Rowan',
    'Doran',
    'Kael',
    'Wystan',
    'Emeric',
    'Faron',
  ],
  givenF: [
    'Maelis',
    'Rowena',
    'Isolde',
    'Adela',
    'Brienne',
    'Sabine',
    'Elspeth',
    'Wynne',
    'Cordia',
    'Yseult',
    'Alys',
    'Mirren',
    'Odette',
    'Rosalind',
    'Serina',
    'Thessaly',
    'Vespera',
    'Aveline',
    'Gwendra',
    'Marisa',
    'Elara',
    'Nesta',
  ],
};

export function placeName(rng: Rng, bank: NameBank = commonNames): string {
  return pick(rng, bank.place1) + pick(rng, bank.place2);
}

export function personName(rng: Rng, sex: 'm' | 'f', bank: NameBank = commonNames): string {
  return pick(rng, sex === 'f' ? bank.givenF : bank.givenM);
}
