import type { TechDef, TechId } from './schema';

/**
 * The M3 tech tree: 20 economy/civic techs across the four ages. Effects are
 * pure Modifier data resolved by sim/modifiers.ts — nothing here needs code.
 * M4 adds the military attack/armor triads and M5 the per-culture uniques as
 * more entries in this table.
 */
export const TECHS: Record<TechId, TechDef> = {
  // ---------------------------- The Founding -------------------------------
  wheelbarrow: {
    id: 'wheelbarrow',
    name: 'Wheelbarrow',
    age: 'founding',
    cost: { food: 60, wood: 40 },
    researchTime: 120,
    researchedAt: 'farm',
    prereqs: [],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.1, resource: 'food' }],
  },
  ironAxes: {
    id: 'ironAxes',
    name: 'Iron Axes',
    age: 'founding',
    cost: { wood: 50, gold: 30 },
    researchTime: 120,
    researchedAt: 'lumberCamp',
    prereqs: [],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.1, resource: 'wood' }],
  },
  stonePicks: {
    id: 'stonePicks',
    name: 'Stone Picks',
    age: 'founding',
    cost: { wood: 40, gold: 30 },
    researchTime: 120,
    researchedAt: 'quarry',
    prereqs: [],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.1, resource: 'stone' }],
  },
  coinage: {
    id: 'coinage',
    name: 'Coinage',
    age: 'founding',
    cost: { wood: 60, gold: 50 },
    researchTime: 120,
    researchedAt: 'market',
    prereqs: [],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.1, resource: 'gold' }],
  },
  timberFraming: {
    id: 'timberFraming',
    name: 'Timber Framing',
    age: 'founding',
    cost: { wood: 80 },
    researchTime: 120,
    researchedAt: 'house',
    prereqs: [],
    effects: [{ stat: 'housingCap', op: 'mul', value: 1.1 }],
  },
  cooperage: {
    id: 'cooperage',
    name: 'Cooperage',
    age: 'founding',
    cost: { wood: 60 },
    researchTime: 120,
    researchedAt: 'storehouse',
    prereqs: [],
    effects: [{ stat: 'storageCap', op: 'mul', value: 1.25 }],
  },

  // ---------------------------- The Flowering ------------------------------
  cropRotation: {
    id: 'cropRotation',
    name: 'Crop Rotation',
    age: 'flowering',
    cost: { food: 150, wood: 80 },
    researchTime: 180,
    researchedAt: 'farm',
    prereqs: ['wheelbarrow'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.15, resource: 'food' }],
  },
  sawmill: {
    id: 'sawmill',
    name: 'Sawmill',
    age: 'flowering',
    cost: { wood: 120, gold: 80 },
    researchTime: 180,
    researchedAt: 'lumberCamp',
    prereqs: ['ironAxes'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.15, resource: 'wood' }],
  },
  quarryCranes: {
    id: 'quarryCranes',
    name: 'Quarry Cranes',
    age: 'flowering',
    cost: { wood: 100, gold: 80 },
    researchTime: 180,
    researchedAt: 'quarry',
    prereqs: ['stonePicks'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.15, resource: 'stone' }],
  },
  caravans: {
    id: 'caravans',
    name: 'Caravans',
    age: 'flowering',
    cost: { food: 100, gold: 120 },
    researchTime: 180,
    researchedAt: 'market',
    prereqs: ['coinage'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.15, resource: 'gold' }],
    unlocks: { buildings: ['guildhall'] },
  },
  masonry: {
    id: 'masonry',
    name: 'Masonry',
    age: 'flowering',
    cost: { wood: 120, stone: 100 },
    researchTime: 180,
    researchedAt: 'quarry',
    prereqs: [],
    effects: [{ stat: 'buildSpeed', op: 'mul', value: 1.15 }],
  },
  herbalism: {
    id: 'herbalism',
    name: 'Herbalism',
    age: 'flowering',
    cost: { food: 120, gold: 60 },
    researchTime: 180,
    researchedAt: 'temple',
    prereqs: [],
    effects: [{ stat: 'popGrowth', op: 'mul', value: 1.15 }],
  },

  // --------------------------- The High Kingdom ----------------------------
  heavyPlough: {
    id: 'heavyPlough',
    name: 'Heavy Plough',
    age: 'highKingdom',
    cost: { food: 300, wood: 150, gold: 100 },
    researchTime: 240,
    researchedAt: 'university',
    prereqs: ['cropRotation'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.15, resource: 'food' }],
  },
  twoManSaw: {
    id: 'twoManSaw',
    name: 'Two-Man Saw',
    age: 'highKingdom',
    cost: { wood: 250, gold: 150 },
    researchTime: 240,
    researchedAt: 'university',
    prereqs: ['sawmill'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.15, resource: 'wood' }],
  },
  banking: {
    id: 'banking',
    name: 'Banking',
    age: 'highKingdom',
    cost: { wood: 200, gold: 300 },
    researchTime: 240,
    researchedAt: 'university',
    prereqs: ['caravans'],
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.2, resource: 'gold' }],
  },
  architecture: {
    id: 'architecture',
    name: 'Architecture',
    age: 'highKingdom',
    cost: { wood: 200, stone: 200 },
    researchTime: 240,
    researchedAt: 'university',
    prereqs: ['masonry'],
    effects: [
      { stat: 'buildSpeed', op: 'mul', value: 1.15 },
      { stat: 'wallHp', op: 'mul', value: 1.2 },
    ],
    unlocks: { buildings: ['keep'] },
  },
  warehousing: {
    id: 'warehousing',
    name: 'Warehousing',
    age: 'highKingdom',
    cost: { wood: 200, gold: 150 },
    researchTime: 240,
    researchedAt: 'university',
    prereqs: ['cooperage'],
    effects: [{ stat: 'storageCap', op: 'mul', value: 1.25 }],
  },
  urbanPlanning: {
    id: 'urbanPlanning',
    name: 'Urban Planning',
    age: 'highKingdom',
    cost: { wood: 250, stone: 150, gold: 100 },
    researchTime: 240,
    researchedAt: 'university',
    prereqs: ['timberFraming'],
    effects: [{ stat: 'housingCap', op: 'mul', value: 1.15 }],
  },

  // ---------------------------- The Golden Age -----------------------------
  physicians: {
    id: 'physicians',
    name: 'Physicians',
    age: 'golden',
    cost: { food: 400, gold: 300 },
    researchTime: 300,
    researchedAt: 'university',
    prereqs: ['herbalism'],
    effects: [{ stat: 'popGrowth', op: 'mul', value: 1.2 }],
  },
  goldenCharter: {
    id: 'goldenCharter',
    name: 'Golden Charter',
    age: 'golden',
    cost: { food: 500, stone: 300, gold: 500 },
    researchTime: 300,
    researchedAt: 'university',
    prereqs: [],
    // unscoped: applies to every resource line
    effects: [{ stat: 'gatherRate', op: 'mul', value: 1.05 }],
  },
};

export const TECH_IDS: readonly TechId[] = Object.keys(TECHS);
