import type { UnitDef, UnitId } from './schema';

/**
 * The v1 unit roster. Counters are data (attackBonuses) and must hold
 * COST-FOR-COST — tests/sim-combat.test.ts enforces the matrix:
 * spearmen beat cavalry, skirmishers beat archers, archers beat militia,
 * rams beat fortifications and little else.
 */
export const UNITS: Record<UnitId, UnitDef> = {
  militia: {
    id: 'militia',
    name: 'Militia',
    tags: ['infantry'],
    cost: { food: 40, gold: 10 },
    trainTime: 30,
    popCost: 1,
    hp: 40,
    attack: 4, // deliberately trash-tier: cheap mass loses to any real composition
    range: 0,
    armor: { melee: 1, pierce: 0 },
    speed: 1.0,
    requiresAge: 'founding',
  },
  spearman: {
    id: 'spearman',
    name: 'Spearman',
    tags: ['infantry'],
    cost: { food: 50, gold: 15 },
    trainTime: 30,
    popCost: 1,
    hp: 45,
    attack: 6,
    range: 0,
    armor: { melee: 1, pierce: 1 },
    speed: 1.0,
    attackBonuses: [{ tag: 'cavalry', mult: 3 }],
    requiresAge: 'founding',
  },
  swordsman: {
    id: 'swordsman',
    name: 'Swordsman',
    tags: ['infantry'],
    cost: { food: 60, gold: 25 },
    trainTime: 35,
    popCost: 1,
    hp: 60,
    attack: 9,
    range: 0,
    armor: { melee: 2, pierce: 1 },
    speed: 1.0,
    requiresAge: 'flowering',
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    tags: ['ranged'],
    cost: { wood: 40, gold: 25 },
    trainTime: 35,
    popCost: 1,
    hp: 30,
    attack: 6,
    range: 4,
    armor: { melee: 0, pierce: 0 },
    speed: 1.0,
    attackBonuses: [{ tag: 'infantry', mult: 2 }],
    requiresAge: 'flowering',
  },
  skirmisher: {
    id: 'skirmisher',
    name: 'Skirmisher',
    tags: ['ranged'],
    cost: { food: 30, wood: 20 },
    trainTime: 30,
    popCost: 1,
    hp: 35,
    attack: 4,
    range: 3,
    armor: { melee: 0, pierce: 3 },
    speed: 1.0,
    attackBonuses: [{ tag: 'ranged', mult: 3 }],
    requiresAge: 'flowering',
  },
  lightCavalry: {
    id: 'lightCavalry',
    name: 'Light Cavalry',
    tags: ['cavalry'],
    cost: { food: 70, gold: 30 },
    trainTime: 40,
    popCost: 1,
    hp: 55,
    attack: 8,
    range: 0,
    armor: { melee: 1, pierce: 1 },
    speed: 1.8,
    attackBonuses: [{ tag: 'ranged', mult: 2 }],
    requiresAge: 'flowering',
  },
  knight: {
    id: 'knight',
    name: 'Knight',
    tags: ['cavalry'],
    cost: { food: 90, gold: 60 },
    trainTime: 50,
    popCost: 1,
    hp: 95,
    attack: 11,
    range: 0,
    armor: { melee: 3, pierce: 2 },
    speed: 1.6,
    requiresAge: 'highKingdom',
  },
  paladin: {
    id: 'paladin',
    name: 'Paladin',
    tags: ['cavalry'],
    cost: { food: 110, gold: 75 },
    trainTime: 55,
    popCost: 1,
    hp: 120,
    attack: 12,
    range: 0,
    armor: { melee: 4, pierce: 3 },
    speed: 1.5,
    requiresAge: 'highKingdom',
    culture: 'valen',
  },
  huscarl: {
    id: 'huscarl',
    name: 'Huscarl',
    tags: ['infantry'],
    cost: { food: 70, gold: 30 },
    trainTime: 40,
    popCost: 1,
    hp: 75,
    attack: 11,
    range: 0,
    armor: { melee: 2, pierce: 3 },
    speed: 1.1,
    requiresAge: 'flowering',
    culture: 'norvik',
  },
  camelRider: {
    id: 'camelRider',
    name: 'Camel Rider',
    tags: ['cavalry'],
    cost: { food: 75, gold: 45 },
    trainTime: 40,
    popCost: 1,
    hp: 65,
    attack: 8,
    range: 0,
    armor: { melee: 1, pierce: 1 },
    speed: 1.7,
    attackBonuses: [{ tag: 'cavalry', mult: 2 }],
    requiresAge: 'flowering',
    culture: 'ashari',
  },
  ram: {
    id: 'ram',
    name: 'Battering Ram',
    tags: ['siege'],
    cost: { wood: 120, gold: 40 },
    trainTime: 60,
    popCost: 2,
    hp: 120,
    attack: 2,
    range: 0,
    armor: { melee: 0, pierce: 8 },
    speed: 0.6,
    siegeMult: 25,
    requiresAge: 'highKingdom',
  },
};

export const UNIT_IDS: readonly UnitId[] = Object.keys(UNITS);
